import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import AuthProvider from "./providers/AuthProvider";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>

          <AuthProvider>
            <NavBar />
            <main className="min-h-screen">
              {children}
              <Toaster position="top-right" reverseOrder={false} />
            </main>
          </AuthProvider>
        </Suspense>

        <Footer />
      </body>
    </html>
  );
}
